def showConf(connDATA):
    print()
    print('Setup from json conf file')
    print('Loading connection parameters')
    print()
    print("User credentials & Stuff")
    print('... Login.host', connDATA['login']['host'])
    print('... Login.user', connDATA['login']['user'])
    print('... Login.pass', connDATA['login']['pass'])
    print()
    print("API credentials & Stuff")
    print('... API.name', connDATA['api']['name'])
    print('... API.user', connDATA['api']['user'])
    print('... API.pass', connDATA['api']['pass'])
    print('... API.tokenUrl', connDATA['api']['tokenUrl'])
    print()
    print("Stomper data")
    print('... Stomp.service', connDATA['stomp']['service'])
    print('... Stomp.port', connDATA['stomp']['port'])
    print()
    print("Endpoints")
    for data in connDATA['endpoint']:
        print('... Enpoints.' + data, connDATA['endpoint'][data])
    print()
    print()


def showToken(conn):
    print()
    # print(conn)
    print("Connection Status")
    print('... access_token', conn['access_token'])
    print('... token_type', conn['token_type'])
    print('... refresh_token', conn['refresh_token'])
    print('... expires_in', conn['expires_in'])
    print('... scope', conn['scope'])
    print('... expires_at', conn['expires_at'])
    print()

